apiVersion: v1
kind: Secret
metadata:
name: adoreal-secrets
namespace: adoreal
stringData:
ConnectionStrings__Default: "Server=localhost\\SQLEXPRESS;Database=AdorealDB;Trusted_Connection=True;TrustServerCertificate=true"